# lg model default - copy to config.yaml
learning_rate: 0.001
emb_dim: 64
dropout: 0.0
n_heads: 4
n_encoder_layers: 4
n_decoder_layers: 4
dim_feedforward: 256
batch_size: 256
validation_batch_size: 256
max_window_size: 256
num_workers: 8
use_lectures: true
use_prior_q_times: true
val_step_frequency: 5000
val_size: 0.10
accumulate_grad_batches: 1
use_agg_feats: True
use_exercise_feats: True