learning_rate: 0.001
emb_dim: 64
dropout: 0.0
n_heads: 2
n_encoder_layers: 2
n_decoder_layers: 2
dim_feedforward: 100
batch_size: 64
max_window_size: 1024
num_workers: 6
use_lectures: True
use_prior_q_times: False
arch_type: base