learning_rate: 0.001
emb_dim: 64
dropout: 0.0
n_heads: 2
n_encoder_layers: 2
n_decoder_layers: 2
dim_feedforward: 256
batch_size: 1
num_user_train: 300000
num_user_val: 30000
max_window_size: 100
num_workers: 0
hydra:
  output_subdir: null
