learning_rate: 0.001
emb_dim: 64
dropout: 0.0
n_heads: 4
n_encoder_layers: 4
n_decoder_layers: 4
dim_feedforward: 256
batch_size: 1024
max_window_size: 100
num_workers: 6
use_lectures: True
use_prior_q_times: False


# hydra:
  # output_subdir: null
#   launcher:
#     n_jobs: 2
# defaults:
#   - hydra/launcher: joblib
